version: "3.5"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./:/app/"
    command: >
      sh -c "python project/manage.py migrate &&
             python project/manage.py loaddata project/fixtures.json &&
             python project/manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"